#!/bin/sh
SCRIPT="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
DIR=`dirname "${SCRIPT}"}`
exec scala $0 $DIR $SCRIPT "$@"
::!#

import scala.sys.process._

object App {
  def main(args: Array[String]): Unit = {
    val start     = args(2).toInt
    val finish    = args(3).toInt
    val increment = args(4).toInt
    val numRuns   = if (args.length >= 6) args(5).toInt
    else 10

    for (len <- (start to finish by increment)) {
      val runBench = "scala -Dsize="+ len +" -cp classes EvactorBench " + numRuns
      runBench.!
    }
  }
}
